[[httpserver]]
== HTTP-провайдер аутентификации
=== Принцип работы

Данный провайдер предполагает, что где-то реализован HTTP-сервис, содержащий в себе три сервлета:

* валидации логина/пароля (по запросу POST данный сервис обязан принимать XML вида:
[source, xml]
<login name="User" password="pass" xmlns="http://www.curs.ru/ns/AuthServer">

* получения информации о пользователе по его логину
* получения информации о пользователе по его GUID

=== Параметры настройки в файле config.xml
Провайдер определяется тэгом *httpserver*.

Параметры (субтэги):

* *logging* (true/false) - выводить в лог события работы провайдера.
* *group_providers* (строка) - группа, к которой относится данный провайдер. Используется для ограничения множества провайдеров, в которые происходит попытка логина. Может быть пустой или отсутствовать. Конкретная группа передается в качестве параметра в сервлете логина, пользователь может иметь возможность явно выбирать группу провайдеров при подключении.
* *url* (строка) - HTTP URL подключения к сервису HTTP.
* *validateuser* (строка) - имя сервлета проверки пары "логин/пароль" пользователя.
* *userinfobyname* (строка) - шаблон ссылки для доступа к информации о пользователе по его логину, где подстановкой %s обозначено место для вставки имени пользователя.
* *userinfobyid* (строка) - шаблон ссылки для доступа к информации о пользователе по его GUID, где подстановкой %s обозначено место для вставки GUID пользователя.
