openapi: 3.0.1
info:
  title: Title
  description: ''
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: mellophone
    description: Меллофон
paths:
  /login:
    get:
      summary: Аутентифицировать сессию
      parameters:
        - name: sesid
          in: query
          description: Идентификатор сессии
          required: true
          schema:
            type: string
      responses:
        200:
          description: Успешно
          content: {}
        403:
          description: Неуспешно
          content:
            text/plain:
              schema:
                type: string
                description: Причина неуспешной аутентификации
    post:
      summary: Аутентифицировать сессию
      requestBody:
        description: Идентификатор сессии
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialsDTO'
      responses:
        200:
          description: Успешно
          content: {}
        403:
          description: Неуспешно
          content:
            text/plain:
              schema:
                type: string
                description: Причина неуспешной аутентификации
components:
  schemas:
    CredentialsDTO:
      type: object
      properties:
        sessid:
          type: string