= Общие настройки

* *threadcount* - количество потоков, параллельно опрашивающих логин-провайдеры (значение по умолчанию 4),
* *sessiontimeout*(целое число) - время жизни сессии в минутах. Нуль или отсутствие значения говорит о бесконечном времени жизни сессии.
* *lockouttime* - время в минутах, на которое будет заблокирован пользователь после loginattemptsallowed неудачных попыток ввода пароля (значение по умолчанию 10).
* *loginattemptsallowed* - количество неудачных попыток ввода пароля до блокировки пользователя (значение по умолчанию 5).
* *setsettingstoken* - токен безопасности для сервлета /setsettings (значение по умолчанию null).
* *getuserlisttoken* - токен безопасности для сервлета /getuserlist (значение по умолчанию null).
* *showtimetounlockuser*(логическое) - показывать ли время, оставшееся до разблокировки пользователя, заблокированного по причине большого количества неудачных попыток ввода пароля.
* *checkpasswordhashonly*(логическое) - настройка типа проверки пароля при логине. Если true будет проверяться только хеш пароля, если false будут проверяться и хеш пароля, и сам пароль (значение по умолчанию false).
* настройки списков аутентификации authsessions и сессий приложений appsessions
** *initialCapacity* - начальная емкость списка (значение по умолчанию 16),
** *loadFactor* - используется списком для определения, когда произойдет увеличение его размера по мере заполнения (значение по умолчанию 75%),
** *concurrencyLevel* - определяет количество сегментов, которое будет содержать список. Количество сегментов будет выбрано как ближайшая степень двойки, большая чем concurrencyLevel. При этом, занижение concurrencyLevel ведёт к тому, что более вероятны блокировки потоками сегментов списка при записи, завышение показателя ведёт к неэффективному использованию памяти (значение по умолчанию 16).

Любые (или все) из этих настроек могут быть не заданы. В таком случае будут использоваться значения по умолчанию.

