name: Check new version is greater than main version

on:
  workflow_call:
    inputs:
      VUH_VERSION: { required: true, type: string }

jobs:

  validate-version:
    name: Check new version is greater than main version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download vuh
        run: |
          curl https://raw.githubusercontent.com/Greewil/version-update-helper/${{ inputs.VUH_VERSION }}/vuh.sh -O -J -L
          chmod +x vuh.sh

      - name: Compare versions
        run: |
          ./vuh.sh sv -q && [ "$(./vuh.sh lv -q)" = "$(./vuh.sh sv -q)" ] || exit 1
